version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-eks: circleci/aws-eks@2.2
  aws-cli: circleci/aws-cli@4.0
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  patch_deployment:
    docker:
      - image: 'cimg/python:3.10'
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
      deployment-name:
        description: |
          Name of the Kubernetes Deployment
        type: string
      kubernetes-namespace:
        description: |
          Name of the Kubernetes namespace the deployment is deployed to
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: ${AWS_REGION}
      - run:
          command: |
            kubectl patch deployment << parameters.deployment-name >> -n << parameters.kubernetes-namespace >> -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"build\":\"${CIRCLE_SHA1}\"}}}}}"
          name: Patch Deployment
workflows:
  build-and-deploy-frontend:
    jobs:
      - aws-ecr/build-and-push-image:
          name: "build-front-dev"
          filters:
            branches:
              only:
                - develop
          extra-build-args: "--build-arg NEXT_PUBLIC_BASE_URL=${DEV_API_URL} --build-arg NEXT_PUBLIC_CLIENT_HOST=${DEV_NEXT_PUBLIC_CLIENT_HOST} --build-arg NODE_ENV=${NODE_ENV_DEV} --build-arg NEXT_PUBLIC_PENDO_API_KEY=${NEXT_PUBLIC_PENDO_API_KEY_DEV} --build-arg NEXT_PUBLIC_INTERCOM_APP_ID=${NEXT_PUBLIC_INTERCOM_APP_ID_DEV}"
          repo: "${ECR_FRONT_DEV}"
          tag: "latest,${CIRCLE_SHA1}"
      - patch_deployment:
          name: "deploy-front-dev"
          filters:
            branches:
              only:
                - develop
          cluster-name: "${EKS_CLUSTER_NAME}"
          deployment-name: "suphub-front-dev"
          kubernetes-namespace: "dev-front"
          requires:
            - build-front-dev
      - aws-ecr/build-and-push-image:
          name: "build-front-prod"
          filters:
            branches:
              only:
                - main  
          extra-build-args: "--build-arg NEXT_PUBLIC_BASE_URL=${PROD_API_URL} --build-arg NEXT_PUBLIC_CLIENT_HOST=${PROD_NEXT_PUBLIC_CLIENT_HOST} --build-arg NODE_ENV=${NODE_ENV_DEV} --build-arg NEXT_PUBLIC_PENDO_API_KEY=${NEXT_PUBLIC_PENDO_API_KEY_PROD} --build-arg NEXT_PUBLIC_INTERCOM_APP_ID=${NEXT_PUBLIC_INTERCOM_APP_ID_PROD}"
          repo: "${ECR_FRONT_PROD}"
          tag: "latest,${CIRCLE_SHA1}"
      - patch_deployment:
          name: "deploy-front-prod"
          filters:
            branches:
              only:
                - main
          cluster-name: "${EKS_CLUSTER_NAME}"
          deployment-name: "suphub-front-prod"
          kubernetes-namespace: "prod-front"
          requires:
            - build-front-prod
