import './../styles/globals.scss';
import { Header } from '@/components/Features/Header';
import { Modal } from '@/components/Modals';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { MainProvider } from '@/Provider/MainProvider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<head>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" />
				<link
					href="https://fonts.googleapis.com/css2?family=Lato:wght@0,100,300,400,700,900&display=swap"
					rel="stylesheet"
				/>
			</head>
			<body>
				<MainProvider>
					<Modal />
					<Header />
					<main className="main">{children}</main>
				</MainProvider>
			</body>
		</html>
	);
}
