import './../styles/globals.scss';
import { Header } from '@/components/Header';
import { Modal } from '@/components/Modals';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { MainProvider } from '@/Provider/MainProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body>
				<MainProvider>
					<Modal />
					<Header />
					<main>{children}</main>
				</MainProvider>
			</body>
		</html>
	);
}
