import { createSlice, PayloadAction } from '@reduxjs/toolkit';

import product_img from '@/imgs/Marketplace/Products/product_test2.jpeg';
import { StaticImageData } from 'next/image';
import { ProductItemType } from '@/types/marketplace/product';

interface Product {
	img: StaticImageData;
	id: number;
	title: string;
	price: number;
	description: {
		[key: string]: string;
	};
}

interface initialStateType {
	products: ProductItemType[];
	favorites: any[];
	activePage: number;
	total: number;
	status: 'pending' | 'seccess' | 'rejected';
}

const initialState: initialStateType = {
	products: [],
	activePage: 1,
	favorites: [
		{
			id: 1,
			name: 'Brickmould Vinyl Sliding Window',
			sku: 'VIY-538',
			unitPrice: 10,
			moq: 40,
			warranty: 5,
			productOverview:
				'Our horizontal sliding windows are made of our exclusive vinyl formula, and are performance tested for excellent weathering, durability and color retention. Sliding windows glide open and closed horizontally for easy access to fresh air.',
			hsCode: '3925.20.0020',
			countryOfOrigin: 'China',
			minOrder: 10,
			leadTime: 4,
			factoryUnitPriceMinQty: 778.69,
			factoryUnitPriceLargeQty: 728.69,
			factoryUnitPriceContainerQty: 678.69,
			containerQty40ft: '85 units',
			containerQty20ft: '40 units',
			platformCommissionRate: 15,
			platformUnitPriceMinQty: 895.49,
			platformUnitPriceLargeQty: 837.99,
			platformUnitPriceContainerQty: 780.49,
			platformOnetimeDiscountedPrice: null,
			sellersUrl:
				'https://www.alibaba.com/product-detail/UPVC-sliding-windows-window-vinyl-pvc_1600901749842.html?spm=a2700.shop_plgr.41413.5.221154a6uk22U1',
			packaging: 'wood pallet + carton corner',
			packageInclude: 'windows',
			packageDimension: '',
			packageWeight: '',
			status: 0,
			largeQty: '40 units',
			unitOfMeasurement: 'unit',
			sellerCompanyId: 1,
			subCategoryId: 1,
			updatedAt: '2023-08-08T12:57:37.644Z',
			createdAt: '2023-08-08T12:57:37.644Z',
			dynamic_attr: [
				{
					attributeId: 10,
					attributeDescription: '',
					label: 'Certification',
					order: 1,
					value: 'AAMA, NFRC',
				},
				{
					attributeId: 1,
					attributeDescription: '',
					label: 'Frame Material',
					order: 2,
					value: 'Steel',
				},
				{
					attributeId: 2,
					attributeDescription: '',
					label: 'Opening Style',
					order: 3,
					value: 'Double-hung',
				},
				{
					attributeId: 3,
					attributeDescription: '',
					label: 'Glazing Type',
					order: 4,
					value: 'Single-pane',
				},
				{
					attributeId: 4,
					attributeDescription: '',
					label: 'Glass Type',
					order: 5,
					value: 'Low-E glass',
				},
				{
					attributeId: 5,
					attributeDescription: 'BTU/h∙ft∙°F',
					label: 'U-Factor',
					order: null,
					value: 0.28,
				},
				{
					attributeId: 6,
					attributeDescription: '',
					label: 'SHGC',
					order: null,
					value: 0.2,
				},
			],
		},
		{
			id: 1,
			name: 'Brickmould Vinyl Sliding Window',
			sku: 'VIY-538',
			unitPrice: 10,
			moq: 40,
			warranty: 5,
			productOverview:
				'Our horizontal sliding windows are made of our exclusive vinyl formula, and are performance tested for excellent weathering, durability and color retention. Sliding windows glide open and closed horizontally for easy access to fresh air.',
			hsCode: '3925.20.0020',
			countryOfOrigin: 'China',
			minOrder: 10,
			leadTime: 4,
			factoryUnitPriceMinQty: 778.69,
			factoryUnitPriceLargeQty: 728.69,
			factoryUnitPriceContainerQty: 678.69,
			containerQty40ft: '85 units',
			containerQty20ft: '40 units',
			platformCommissionRate: 15,
			platformUnitPriceMinQty: 895.49,
			platformUnitPriceLargeQty: 837.99,
			platformUnitPriceContainerQty: 780.49,
			platformOnetimeDiscountedPrice: null,
			sellersUrl:
				'https://www.alibaba.com/product-detail/UPVC-sliding-windows-window-vinyl-pvc_1600901749842.html?spm=a2700.shop_plgr.41413.5.221154a6uk22U1',
			packaging: 'wood pallet + carton corner',
			packageInclude: 'windows',
			packageDimension: '',
			packageWeight: '',
			status: 0,
			largeQty: '40 units',
			unitOfMeasurement: 'unit',
			sellerCompanyId: 1,
			subCategoryId: 1,
			updatedAt: '2023-08-08T12:57:37.644Z',
			createdAt: '2023-08-08T12:57:37.644Z',
			dynamic_attr: [
				{
					attributeId: 10,
					attributeDescription: '',
					label: 'Certification',
					order: 1,
					value: 'AAMA, NFRC',
				},
				{
					attributeId: 1,
					attributeDescription: '',
					label: 'Frame Material',
					order: 2,
					value: 'Steel',
				},
				{
					attributeId: 2,
					attributeDescription: '',
					label: 'Opening Style',
					order: 3,
					value: 'Double-hung',
				},
				{
					attributeId: 3,
					attributeDescription: '',
					label: 'Glazing Type',
					order: 4,
					value: 'Single-pane',
				},
				{
					attributeId: 4,
					attributeDescription: '',
					label: 'Glass Type',
					order: 5,
					value: 'Low-E glass',
				},
				{
					attributeId: 5,
					attributeDescription: 'BTU/h∙ft∙°F',
					label: 'U-Factor',
					order: null,
					value: 0.28,
				},
				{
					attributeId: 6,
					attributeDescription: '',
					label: 'SHGC',
					order: null,
					value: 0.2,
				},
			],
		},
		{
			id: 1,
			name: 'Brickmould Vinyl Sliding Window',
			sku: 'VIY-538',
			unitPrice: 10,
			moq: 40,
			warranty: 5,
			productOverview:
				'Our horizontal sliding windows are made of our exclusive vinyl formula, and are performance tested for excellent weathering, durability and color retention. Sliding windows glide open and closed horizontally for easy access to fresh air.',
			hsCode: '3925.20.0020',
			countryOfOrigin: 'China',
			minOrder: 10,
			leadTime: 4,
			factoryUnitPriceMinQty: 778.69,
			factoryUnitPriceLargeQty: 728.69,
			factoryUnitPriceContainerQty: 678.69,
			containerQty40ft: '85 units',
			containerQty20ft: '40 units',
			platformCommissionRate: 15,
			platformUnitPriceMinQty: 895.49,
			platformUnitPriceLargeQty: 837.99,
			platformUnitPriceContainerQty: 780.49,
			platformOnetimeDiscountedPrice: null,
			sellersUrl:
				'https://www.alibaba.com/product-detail/UPVC-sliding-windows-window-vinyl-pvc_1600901749842.html?spm=a2700.shop_plgr.41413.5.221154a6uk22U1',
			packaging: 'wood pallet + carton corner',
			packageInclude: 'windows',
			packageDimension: '',
			packageWeight: '',
			status: 0,
			largeQty: '40 units',
			unitOfMeasurement: 'unit',
			sellerCompanyId: 1,
			subCategoryId: 1,
			updatedAt: '2023-08-08T12:57:37.644Z',
			createdAt: '2023-08-08T12:57:37.644Z',
			dynamic_attr: [
				{
					attributeId: 10,
					attributeDescription: '',
					label: 'Certification',
					order: 1,
					value: 'AAMA, NFRC',
				},
				{
					attributeId: 1,
					attributeDescription: '',
					label: 'Frame Material',
					order: 2,
					value: 'Steel',
				},
				{
					attributeId: 2,
					attributeDescription: '',
					label: 'Opening Style',
					order: 3,
					value: 'Double-hung',
				},
				{
					attributeId: 3,
					attributeDescription: '',
					label: 'Glazing Type',
					order: 4,
					value: 'Single-pane',
				},
				{
					attributeId: 4,
					attributeDescription: '',
					label: 'Glass Type',
					order: 5,
					value: 'Low-E glass',
				},
				{
					attributeId: 5,
					attributeDescription: 'BTU/h∙ft∙°F',
					label: 'U-Factor',
					order: null,
					value: 0.28,
				},
				{
					attributeId: 6,
					attributeDescription: '',
					label: 'SHGC',
					order: null,
					value: 0.2,
				},
			],
		},
		{
			id: 1,
			name: 'Brickmould Vinyl Sliding Window',
			sku: 'VIY-538',
			unitPrice: 10,
			moq: 40,
			warranty: 5,
			productOverview:
				'Our horizontal sliding windows are made of our exclusive vinyl formula, and are performance tested for excellent weathering, durability and color retention. Sliding windows glide open and closed horizontally for easy access to fresh air.',
			hsCode: '3925.20.0020',
			countryOfOrigin: 'China',
			minOrder: 10,
			leadTime: 4,
			factoryUnitPriceMinQty: 778.69,
			factoryUnitPriceLargeQty: 728.69,
			factoryUnitPriceContainerQty: 678.69,
			containerQty40ft: '85 units',
			containerQty20ft: '40 units',
			platformCommissionRate: 15,
			platformUnitPriceMinQty: 895.49,
			platformUnitPriceLargeQty: 837.99,
			platformUnitPriceContainerQty: 780.49,
			platformOnetimeDiscountedPrice: null,
			sellersUrl:
				'https://www.alibaba.com/product-detail/UPVC-sliding-windows-window-vinyl-pvc_1600901749842.html?spm=a2700.shop_plgr.41413.5.221154a6uk22U1',
			packaging: 'wood pallet + carton corner',
			packageInclude: 'windows',
			packageDimension: '',
			packageWeight: '',
			status: 0,
			largeQty: '40 units',
			unitOfMeasurement: 'unit',
			sellerCompanyId: 1,
			subCategoryId: 1,
			updatedAt: '2023-08-08T12:57:37.644Z',
			createdAt: '2023-08-08T12:57:37.644Z',
			dynamic_attr: [
				{
					attributeId: 10,
					attributeDescription: '',
					label: 'Certification',
					order: 1,
					value: 'AAMA, NFRC',
				},
				{
					attributeId: 1,
					attributeDescription: '',
					label: 'Frame Material',
					order: 2,
					value: 'Steel',
				},
				{
					attributeId: 2,
					attributeDescription: '',
					label: 'Opening Style',
					order: 3,
					value: 'Double-hung',
				},
				{
					attributeId: 3,
					attributeDescription: '',
					label: 'Glazing Type',
					order: 4,
					value: 'Single-pane',
				},
				{
					attributeId: 4,
					attributeDescription: '',
					label: 'Glass Type',
					order: 5,
					value: 'Low-E glass',
				},
				{
					attributeId: 5,
					attributeDescription: 'BTU/h∙ft∙°F',
					label: 'U-Factor',
					order: null,
					value: 0.28,
				},
				{
					attributeId: 6,
					attributeDescription: '',
					label: 'SHGC',
					order: null,
					value: 0.2,
				},
			],
		},
		{
			id: 1,
			name: 'Brickmould Vinyl Sliding Window',
			sku: 'VIY-538',
			unitPrice: 10,
			moq: 40,
			warranty: 5,
			productOverview:
				'Our horizontal sliding windows are made of our exclusive vinyl formula, and are performance tested for excellent weathering, durability and color retention. Sliding windows glide open and closed horizontally for easy access to fresh air.',
			hsCode: '3925.20.0020',
			countryOfOrigin: 'China',
			minOrder: 10,
			leadTime: 4,
			factoryUnitPriceMinQty: 778.69,
			factoryUnitPriceLargeQty: 728.69,
			factoryUnitPriceContainerQty: 678.69,
			containerQty40ft: '85 units',
			containerQty20ft: '40 units',
			platformCommissionRate: 15,
			platformUnitPriceMinQty: 895.49,
			platformUnitPriceLargeQty: 837.99,
			platformUnitPriceContainerQty: 780.49,
			platformOnetimeDiscountedPrice: null,
			sellersUrl:
				'https://www.alibaba.com/product-detail/UPVC-sliding-windows-window-vinyl-pvc_1600901749842.html?spm=a2700.shop_plgr.41413.5.221154a6uk22U1',
			packaging: 'wood pallet + carton corner',
			packageInclude: 'windows',
			packageDimension: '',
			packageWeight: '',
			status: 0,
			largeQty: '40 units',
			unitOfMeasurement: 'unit',
			sellerCompanyId: 1,
			subCategoryId: 1,
			updatedAt: '2023-08-08T12:57:37.644Z',
			createdAt: '2023-08-08T12:57:37.644Z',
			dynamic_attr: [
				{
					attributeId: 10,
					attributeDescription: '',
					label: 'Certification',
					order: 1,
					value: 'AAMA, NFRC',
				},
				{
					attributeId: 1,
					attributeDescription: '',
					label: 'Frame Material',
					order: 2,
					value: 'Steel',
				},
				{
					attributeId: 2,
					attributeDescription: '',
					label: 'Opening Style',
					order: 3,
					value: 'Double-hung',
				},
				{
					attributeId: 3,
					attributeDescription: '',
					label: 'Glazing Type',
					order: 4,
					value: 'Single-pane',
				},
				{
					attributeId: 4,
					attributeDescription: '',
					label: 'Glass Type',
					order: 5,
					value: 'Low-E glass',
				},
				{
					attributeId: 5,
					attributeDescription: 'BTU/h∙ft∙°F',
					label: 'U-Factor',
					order: null,
					value: 0.28,
				},
				{
					attributeId: 6,
					attributeDescription: '',
					label: 'SHGC',
					order: null,
					value: 0.2,
				},
			],
		},
		{
			id: 1,
			name: 'Brickmould Vinyl Sliding Window',
			sku: 'VIY-538',
			unitPrice: 10,
			moq: 40,
			warranty: 5,
			productOverview:
				'Our horizontal sliding windows are made of our exclusive vinyl formula, and are performance tested for excellent weathering, durability and color retention. Sliding windows glide open and closed horizontally for easy access to fresh air.',
			hsCode: '3925.20.0020',
			countryOfOrigin: 'China',
			minOrder: 10,
			leadTime: 4,
			factoryUnitPriceMinQty: 778.69,
			factoryUnitPriceLargeQty: 728.69,
			factoryUnitPriceContainerQty: 678.69,
			containerQty40ft: '85 units',
			containerQty20ft: '40 units',
			platformCommissionRate: 15,
			platformUnitPriceMinQty: 895.49,
			platformUnitPriceLargeQty: 837.99,
			platformUnitPriceContainerQty: 780.49,
			platformOnetimeDiscountedPrice: null,
			sellersUrl:
				'https://www.alibaba.com/product-detail/UPVC-sliding-windows-window-vinyl-pvc_1600901749842.html?spm=a2700.shop_plgr.41413.5.221154a6uk22U1',
			packaging: 'wood pallet + carton corner',
			packageInclude: 'windows',
			packageDimension: '',
			packageWeight: '',
			status: 0,
			largeQty: '40 units',
			unitOfMeasurement: 'unit',
			sellerCompanyId: 1,
			subCategoryId: 1,
			updatedAt: '2023-08-08T12:57:37.644Z',
			createdAt: '2023-08-08T12:57:37.644Z',
			dynamic_attr: [
				{
					attributeId: 10,
					attributeDescription: '',
					label: 'Certification',
					order: 1,
					value: 'AAMA, NFRC',
				},
				{
					attributeId: 1,
					attributeDescription: '',
					label: 'Frame Material',
					order: 2,
					value: 'Steel',
				},
				{
					attributeId: 2,
					attributeDescription: '',
					label: 'Opening Style',
					order: 3,
					value: 'Double-hung',
				},
				{
					attributeId: 3,
					attributeDescription: '',
					label: 'Glazing Type',
					order: 4,
					value: 'Single-pane',
				},
				{
					attributeId: 4,
					attributeDescription: '',
					label: 'Glass Type',
					order: 5,
					value: 'Low-E glass',
				},
				{
					attributeId: 5,
					attributeDescription: 'BTU/h∙ft∙°F',
					label: 'U-Factor',
					order: null,
					value: 0.28,
				},
				{
					attributeId: 6,
					attributeDescription: '',
					label: 'SHGC',
					order: null,
					value: 0.2,
				},
			],
		},
		{
			id: 1,
			name: 'Brickmould Vinyl Sliding Window',
			sku: 'VIY-538',
			unitPrice: 10,
			moq: 40,
			warranty: 5,
			productOverview:
				'Our horizontal sliding windows are made of our exclusive vinyl formula, and are performance tested for excellent weathering, durability and color retention. Sliding windows glide open and closed horizontally for easy access to fresh air.',
			hsCode: '3925.20.0020',
			countryOfOrigin: 'China',
			minOrder: 10,
			leadTime: 4,
			factoryUnitPriceMinQty: 778.69,
			factoryUnitPriceLargeQty: 728.69,
			factoryUnitPriceContainerQty: 678.69,
			containerQty40ft: '85 units',
			containerQty20ft: '40 units',
			platformCommissionRate: 15,
			platformUnitPriceMinQty: 895.49,
			platformUnitPriceLargeQty: 837.99,
			platformUnitPriceContainerQty: 780.49,
			platformOnetimeDiscountedPrice: null,
			sellersUrl:
				'https://www.alibaba.com/product-detail/UPVC-sliding-windows-window-vinyl-pvc_1600901749842.html?spm=a2700.shop_plgr.41413.5.221154a6uk22U1',
			packaging: 'wood pallet + carton corner',
			packageInclude: 'windows',
			packageDimension: '',
			packageWeight: '',
			status: 0,
			largeQty: '40 units',
			unitOfMeasurement: 'unit',
			sellerCompanyId: 1,
			subCategoryId: 1,
			updatedAt: '2023-08-08T12:57:37.644Z',
			createdAt: '2023-08-08T12:57:37.644Z',
			dynamic_attr: [
				{
					attributeId: 10,
					attributeDescription: '',
					label: 'Certification',
					order: 1,
					value: 'AAMA, NFRC',
				},
				{
					attributeId: 1,
					attributeDescription: '',
					label: 'Frame Material',
					order: 2,
					value: 'Steel',
				},
				{
					attributeId: 2,
					attributeDescription: '',
					label: 'Opening Style',
					order: 3,
					value: 'Double-hung',
				},
				{
					attributeId: 3,
					attributeDescription: '',
					label: 'Glazing Type',
					order: 4,
					value: 'Single-pane',
				},
				{
					attributeId: 4,
					attributeDescription: '',
					label: 'Glass Type',
					order: 5,
					value: 'Low-E glass',
				},
				{
					attributeId: 5,
					attributeDescription: 'BTU/h∙ft∙°F',
					label: 'U-Factor',
					order: null,
					value: 0.28,
				},
				{
					attributeId: 6,
					attributeDescription: '',
					label: 'SHGC',
					order: null,
					value: 0.2,
				},
			],
		},
	],
	total: 0,
	status: 'pending',
};

const productSlice = createSlice({
	name: 'filters',
	initialState,
	reducers: {
		setActivePage(state, action: PayloadAction<number>) {
			state.activePage = action.payload;
		},
		setProducts(state, action: PayloadAction<ProductItemType[]>) {
			state.products = action.payload;
		},
		setTotal(state, action: PayloadAction<number>) {
			state.total = action.payload;
		},
		setStatus(state, action: PayloadAction<'pending' | 'seccess' | 'rejected'>) {
			state.status = action.payload;
		},
	},
});

export const { setActivePage, setProducts, setTotal, setStatus } =
	productSlice.actions;

export default productSlice.reducer;
