import type { Metadata } from 'next';
import SettingsSidebar from '@/components/Screens/ProfileSettings/Sidebar';
import s from '@/components/Screens/ProfileSettings/SettingsLayout.module.scss'

export const metadata: Metadata = {
	title: 'Suphub Profile Settings',
	description: 'Generated by create next app',
};

export default function SettingsLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className={s.settings_main}>
			<SettingsSidebar/>
			<div className={s.settings_children}>{children}</div>
		</div>
	);
}